### PR TITLE
Update and revamp

### LINKED ISSUE #4: Allow "xlink:href" and other attributes with colons
I see in map.json that `xlinkhref` translates to `xlinkHref`. What about `xlink:href`, which is how I think it would appear in HTML?

Is there a reason I don't understand, or are you open to a PR fixing this?

### PR DESCRIPTION
**Pull request by davidtheclark**
Closes #4 and other potential similar issues by 
  - Revamping the source data. I set it up in arrays that can be easily updated from pages of React documentation. Copied everything from React documentation today to ensure it's all up to date.
  - Removing hyphens and colons from the original attribute when looking for a replacement value.

Also:
  - Handles ARIA attributes the same way data-* attributes are handled (just passes them through).
  - Updates AVA and Node version for Travis.

@noraesae what do you think?

### CODE REVIEW

**Comment by hatashiro** [comment]
Hmm, I may stick to the original mapping method. Looking up an array is more expensive than looking up a map.

Other part seems good. I'm really sorry but can you revert the looking-up part? Or I may just merge this and upload follow-ups by myself.

**Comment by hatashiro** [comment]
Thanks!

**Comment by davidtheclark** [comment]
@noraesae: 🤔  ... my reasoning for using the arrays was to make it easier to update. But I guess it shouldn't need to update very often. Let me know if you'd like any help changing the format back to a map!

**Comment by hatashiro** [comment]
Yes, it may not be updated frequently, and it's also easy enough to add. I've made follow-ups. Thanks!

**Pull request merged**
